export const FETCH_FEED_DATA = "FETCH_FEED_FEEDBACKS_DATA";
export const FETCH_FEED_DATA_SUCCEEDED  = "FETCH_FEED_FEEDBACKS_DATA_SUCCEEDED";
export const FETCH_FEED_DATA_ERROR  = "FETCH_FEED_FEEDBACKS_DATA_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS_FEEDBACKS";