export const FETCH_FEED_DATA = "FETCH_FEED_TIMINGS_DATA";
export const FETCH_FEED_DATA_SUCCEEDED  = "FETCH_FEED_TIMINGS_DATA_SUCCEEDED";
export const FETCH_FEED_DATA_ERROR  = "FETCH_FEED_TIMINGS_DATA_ERROR";
export const UPDATE_FILTERS = "UPDATE_FILTERS_TIMINGS";